unit_test (unittest.loader._FailedTest.unit_test) ... ERROR

======================================================================
ERROR: unit_test (unittest.loader._FailedTest.unit_test)
----------------------------------------------------------------------
ImportError: Failed to import test module: unit_test
Traceback (most recent call last):
  File "/usr/lib/python3.11/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/testing/student_module/unit_test.py", line 2, in <module>
    from main.py import test_sum
ModuleNotFoundError: No module named 'main.py'; 'main' is not a package


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
